# version catalog can be used in any gradle build, simply add
#
# dependencyResolutionManagement {
#   versionCatalogs {
#     create("libs") {
#       from(files("path/to/libs.versions.toml"))
#     }
#   }
# }
#
# to settings.gradle.kts to include the version catalog in your build.
# any settings.gradle.kts works!
# see https://docs.gradle.org/current/userguide/platforms.html#sec:sharing-catalogs for more details
[versions]
# java version is defined in my-java-base.gradle.kts
# lib versions
kotlin = "1.7.21"
springBoot = "2.7.5"
kotest = "5.5.4"
kotestSpring = "1.1.2"
mockitoKotlin = "4.0.0"
mockk = "1.13.2"
springMockk = "3.1.1"
# plugin versions
gradleVersions = "0.44.0"
versionCatalogUpdater = "0.7.0"
springDependencyManagement = "1.0.15.RELEASE"
kInlineLogging = "1.0.1"
freefairPlugins = "6.5.1"

[libraries]
# naming convention: <artifact>
# unless there is a keyword conflict or the name is wired
# bom
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
# plugin dependencies
gradle-versions-plugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradleVersions" }
gradle-version-catalog-update-plugin = { module = "nl.littlerobots.vcu:plugin", version.ref = "versionCatalogUpdater" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
spring-dependency-management-plugin = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "springDependencyManagement" }
lombok-gradle-plugin = { module = "io.freefair.lombok:io.freefair.lombok.gradle.plugin", version.ref = "freefairPlugins" }
# dependencies
kotlin-jvm-inline-logging = { module = "com.github.CXwudi:kotlin-jvm-inline-logging", version.ref = "kInlineLogging" }
kotest-extensions-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version.ref = "kotestSpring" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
spring-mockk = { module = "com.ninja-squad:springmockk", version.ref = "springMockk" }
